config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  
  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  def to_s
    "##{id} - #{frente}"
  end

  def name
    "##{id} - #{frente} -> #{verso}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :target_card, only: [:edit, :update]
	def index
		@cards = Card.all
	end

  def show
    @card = Card.find_by(id: params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    card = Card.create(card_params)

    redirect_to card_url(card)
  end

  def edit
  end

  def update
    @card.update(card_params)

    redirect_to card_url(@card)
  end

  private

  def target_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:frente, :verso)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
  <%= f.text_field :frente, placeholder: 'Frente' %>
  <%= f.text_field :verso, placeholder: 'Verso' %>
  <%= f.submit submit %>
<% end %>

app/views/cards/edit.html.erb
<h1>Editar Card</h1>

<%= render 'form', submit: 'Editar!' %>

app/views/cards/index.html.erb
<h1>Lista de Cards</h1>

<% @cards.each do |card| %>
	<p><%= link_to card, card %></p>
<% end %>

<button><%= link_to 'Criar card', new_card_path %></button>

app/views/cards/new.html.erb
<h1>Novo Card</h1>

<%= render 'form', submit: 'Criar!' %>

app/views/cards/show.html.erb
<h1>Detalhe do Card</h1>

<% if @card.nil? %>
  <p>Esse card não existe!</p>
<% else %>
  <p><%= @card.name %> (<%= link_to 'Editar', edit_card_path(@card) %>)</p>
<% end %>

<button><%= link_to 'Voltar', root_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>campuscode_cards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>